### ISSUE TITLE
Minor typos and errors

### ISSUE THREAD

**Issue by tommygebru** [Philipwallen/codecademy_projects#1]
Sometimes these things require a second pair of eyes, but proper syntax and formatting is very important to get the desired output in web pages and apps. Pay attention to minor errors like spelling and typos, consider installing a “Spell-check” extension for your code editor, as well as other helpful “Linters” that check for coding errors

- Missing `title `tags, from the` head` element
- Use the `html entity` for the _ampersand_ character 
https://developer.mozilla.org/en-US/docs/Glossary/Entity
- Missing closing tag for **heading 2** on line 22

**Comment by Philipwallen** [comment]
What would be a good spelling check program/application do download for developers?

**Comment by tommygebru** [comment]
There are many online versions of these tools to bookmark, but if you can find some that are within your editor it may be even more helpful. For example, if you use atom editor, you may find this useful https://www.shopify.com/partners/blog/best-atom-packages-2017
