### ISSUE TITLE
Best Practices, indentation and nesting

### ISSUE THREAD

**Issue by tommygebru** [Philipwallen/codecademy_projects#2]
Great work on formatting your code with Indentation, your code points out the nested elements and distinguish between parent/child elements

Below I wrote an example of the nest/wrap relationship, another name for it would be the parent/child relationship.
```

<div class=”wrapping” >
     <p class=”nesting”></p>
     <p class=”nesting”></p>
</div>

```
or
```

<div class=”parent” >
     <p class=”children”></p>
     <p class=”children”></p>
</div>

```

**Comment by Philipwallen** [comment]
This comment stops at "or" I believe you were adding more to the message or I just don't know how to access the remainder of the message.
