### ISSUE TITLE
Dont Repeat Yourself (or DRY method)

### ISSUE THREAD

**Issue by tommygebru** [Philipwallen/codecademy_projects#4]
Consider applying css styles to the html elements once, instead of having to write out the following styles:
```
font-family: Helvetica;
font-size: 32px;
font-weight: bold;
color: white;
```
 in your css document multiple times. These styles could be assigned to the entire page with the html, body selectors or even use stacking technique.
_for example_
`h1, h2, p {color: orange}`

**Comment by Philipwallen** [comment]
I thought about that and I have actually applied this to code that I have written since submitting this for code review.   Thanks again.
