### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by tommygebru** [Philipwallen/codecademy_projects#8]
Hey Philip, don't worry too much about the score, you're project was pretty good. You have a solid grasp of some of the best practices of html and css.

Spend a little more time reviewing/practicing upon the feedback until it clicks, and I'm confident you'll do fine.

Lastly keep some HTML/CSS best practices in mind when coding
https://www.codecademy.com/articles
https://github.com/thenerdery/html-css-standards
When in doubt Google it (or MDN it) 🎉
Ok Philip keep up the good work and happy coding!

**Comment by Philipwallen** [comment]
Tommy, receiving 15 of 16 on the first project that I have completed for any program anywhere gives me a positive stepping stone to grow from.  Thanks for the feedback and I look forward to the next opportunity to put my work on display again.
